### PR TITLE
Add new tool: oca-repo-add-branch

### PR DESCRIPTION
**Pull request by simahawk**
Addresses 2 items of the usual flow to setup new Odoo version's branches:
* add new branch to all repos
* set it as default

Result for v18 https://github.com/OCA/repo-maintainer-conf/pull/36

### CODE REVIEW

**Comment by simahawk** [comment]
I still have to address the use case to reuse answers from previous branch https://github.com/OCA/maintainer-tools/pull/541

**Comment by simahawk** [comment]
To fix: preserve `master` branch defaults for tools' repo.

**Comment by simahawk** [comment]
> To fix: preserve `master` branch defaults for tools' repo.

Fixed here https://github.com/OCA/repo-maintainer/pull/20/commits/b3b14256d0f14c6dd41dac9b6a04851ed66c54ee

**Comment by simahawk** [comment]
@etobella when you have time... ;)

**Review by rousseldenis — APPROVED** [review]

**Comment by rousseldenis** [comment]
@etobella

**Comment by simahawk** [comment]
The files are ready on the conf. If we have to fix something we can do it manually there. This is just a manual tool to edit files.

**Pull request merged**
